# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L7FOZlRUNeLh6GrL7mFr6UfIAuR7fDvs
"""

import tensorflow as tf
import numpy as np

from tensorflow import keras
import pandas as pd
from sklearn.preprocessing import StandardScaler,LabelEncoder
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from google.colab import drive
drive.mount('/content/drive')

data=pd.read_csv("/content/diabetes.csv")

data.head()

data.isnull().sum()

X=data.drop(labels=['Outcome'],axis=1)
Y=data['Outcome']

X.dtypes



scaler=StandardScaler()
X=scaler.fit_transform(X)
X

X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)

X_train.shape

model1=keras.models.Sequential()
model1.add(keras.layers.Dense(128,activation='relu',input_dim=X_train.shape[1]))
model1.add(keras.layers.Dense(64,activation='relu'))
model1.add(keras.layers.Dense(32,activation='relu'))
model1.add(keras.layers.Dense(1,activation='hard_sigmoid'))
model1.compile(loss='binary_crossentropy',optimizer='adamax',metrics=['accuracy'])

r=model1.fit(X_train,Y_train,batch_size=20,epochs=40,validation_data=(X_test,Y_test))

test_scores=model1.evaluate(X_test,Y_test)
print('Test Loss:',test_scores[0])
print('Test accuracy:',test_scores[1]*100)